// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Components from "@tarojs/components";

import './index.less'
;

function PageIndex(Props) {
  return React.createElement(Components.View, {
              className: "index",
              children: React.createElement(Components.Text, {
                    children: "Hello Rescript!"
                  })
            });
}

var make = PageIndex;

var $$default = PageIndex;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/*  Not a pure module */
